# Generated by Django 3.1.5 on 2021-01-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('is_short_task', models.BooleanField(verbose_name='is short')),
                ('is_jira', models.BooleanField(verbose_name='is jira')),
                ('soft_prio', models.IntegerField(default=0)),
                ('hard_prio', models.IntegerField(default=0)),
            ],
        ),
    ]
