# Generated by Django 3.1.5 on 2021-01-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20210113_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation-date'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_jira',
            field=models.BooleanField(verbose_name='is-jira'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_short_task',
            field=models.BooleanField(verbose_name='is-short'),
        ),
    ]
